name: CI
on:
  pull_request:
  push:
    branches:
      - master

env:
  INFLUXDB_ADMIN_TOKEN: DUMMYTOKEN

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      influxdb:
        image: influxdb:2.1-alpine
        env:
          DOCKER_INFLUXDB_INIT_USERNAME: test
          DOCKER_INFLUXDB_INIT_PASSWORD: test_password1
          DOCKER_INFLUXDB_INIT_ORG: test
          DOCKER_INFLUXDB_INIT_BUCKET: test
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${{ env.INFLUXDB_ADMIN_TOKEN }}
          DOCKER_INFLUXDB_INIT_MODE: setup
        ports:
          - "8086:8086"
    strategy:
      matrix:
        python_version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: ${{ matrix.python_version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/artifacts
            ~/.cache/pypoetry/cache/repositories
            ~/.cache/pip
          key: ${{ matrix.python_version }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ matrix.python_version }}-pip-
      - uses: abatilo/actions-poetry@v2.1.5
      - name: Install dependencies
        run: |
          poetry install --no-root --remove-untracked
      - name: Run test
        run: |
          ./wait-for-it.sh localhost:8086
          poetry run pytest --cov aioinfluxdb --cov-config pyproject.toml --cov-report 'xml:./coverage.xml' ./tests
        env:
          INFLUXDB_HOST: localhost
          INFLUXDB_ADMIN_TOKEN: ${{ env.INFLUXDB_ADMIN_TOKEN }}
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: "${{ matrix.python_version }}"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry/artifacts
            ~/.cache/pypoetry/cache/repositories
            ~/.cache/pip
          key: ${{ matrix.python_version }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ matrix.python_version }}-pip-
      - uses: abatilo/actions-poetry@v2.1.5
      - name: Install dependencies
        run: |
          poetry install --no-root --remove-untracked
      - name: Run black
        run: |
          poetry run black aioinfluxdb --check
